name: Build Self-Hosted

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, docker]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
